apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-scale
spec:
  scaleTargetRef:
    name: sample-app
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: cpu
    metadata:
      value: "50"