apiVersion: karpenter.k8s.aws/v1   # ✅ FIX HERE
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  role: KarpenterNodeRole
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-learning
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: eks-learning